port: 80
frontend_dir: "./web/statics"               # For linux we recommend "/var/web/plannet/statics"
authed_path_name: "/me"
jwt_secret: "abc"                         # Use something safer here
db_dir: "/home/llambdaa/Downloads/xmldb"  # For linux we recommend "/var/xmldb"