port: 80
static_dir: "./web/statics"     # For linux we recommend "/var/web/plannet/statics"
html_dir: "./web/html"          # For linux we recommend "/var/web/plannet/html"
authed_path_name: "/c"
jwt_secret: "abc"               # Use something safer here
db_root_dir: "./xmldb"          # For linux we recommend "/var/xmldb"