port: 80
static_dir: "./web/statics"     # For linux we recommend "/var/web/statics"
html_dir: "./web/html"          # For linux we recommend "/var/web/html"
authed_path_name: "/c"
db_root_dir: "./xmldb"          # For linux we recommend "/var/xmldb"